//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.02.13 at 06:23:14 PM YEKT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://akhtyamov.com/springeshop/ws/products", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.akhtyamov.springeshop.ws.products;
