spring:
  jpa:
    hibernate:
      ddl-auto: validate #update #validate
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/shop
    username: postgres
    password: admin
  flyway:
    baseline-on-migrate: true
  thymeleaf:
    cache: false
    prefix: classpath:/templates/

  cloud:
    config:
      import-check:
        enabled: false
#Настройки для конфигурации реализации функционала связанного с EMAIL
server:
  hostname: localhost
  port: ${PORT:8080}
mail:
  server:
    host: smtp.mail.ru #smtp.gmail.com
    port: 587
    username: ahtyamovden@mail.ru
    password: TESTSTES
#---
#spring:
#  application:
#    name: spring-eshop-client
#
#  config:
#    import: optional:configserver:http://localhost:8888
